/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/novels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Novels */
        get: operations["list_novels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/{timestamp}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chapters */
        get: operations["list_chapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/{timestamp}/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chapter Detail */
        get: operations["get_chapter_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/{timestamp}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/{timestamp}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph Data */
        get: operations["get_graph_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/{timestamp}/entity/{entity_name}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity Timeline
         * @description Get the chronological timeline of events for a specific entity.
         */
        get: operations["get_entity_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Relationship Cache
         * @description Delete cached relationship analysis for a specific pair.
         */
        delete: operations["delete_relationship_cache"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_name}/{file_hash}/{timestamp}/relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Relationship Timeline
         * @description Get the interaction timeline between two entities (bidirectional).
         *     Returns a list of interactions where Source->Target OR Target->Source.
         *     Also returns the Narrative State (Trust, Romance, etc.) if available.
         */
        get: operations["get_relationship_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/batch-relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Batch Relationship Job
         * @description Submit a batch relationship analysis job.
         */
        post: operations["submit_batch_relationship_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Relationship Job
         * @description Submit a background job to analyze relationship arc.
         */
        post: operations["submit_relationship_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Status */
        get: operations["get_job_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchRelationshipJobRequest */
        BatchRelationshipJobRequest: {
            /** Novel Name */
            novel_name: string;
            /** File Hash */
            file_hash: string;
            /** Pairs */
            pairs: components["schemas"]["RelationshipPair"][];
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** ChapterDetail */
        ChapterDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Headline */
            headline?: string | null;
            /** Content */
            content: string;
            /** Summary Sentences */
            summary_sentences: components["schemas"]["SummarySentence"][];
            /**
             * Entities
             * @default []
             */
            entities: components["schemas"]["EntityDetail"][];
        };
        /** ChapterPreview */
        ChapterPreview: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Headline */
            headline: string;
            /**
             * Has Summary
             * @default true
             */
            has_summary: boolean;
        };
        /** EdgeEvent */
        EdgeEvent: {
            /** Chapter Id */
            chapter_id: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /** Relation */
            relation?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /**
         * EntityDetail
         * @description 继承 BaseEntity
         */
        EntityDetail: {
            /**
             * Name
             * @description 实体名称 (如 '孙杰克', '玄天宗')
             */
            name: string;
            /**
             * Type
             * @description 实体类型: Person(人物), Location(地点/自然环境), Organization(组织/社会环境), Item(物品), Concept(概念)
             */
            type: string;
            /**
             * Description
             * @description 相关描述或状态更新
             */
            description: string;
            /**
             * Confidence
             * @description 置信度
             */
            confidence?: number | null;
        };
        /** GraphData */
        GraphData: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Weight */
            weight: number;
            /**
             * Timeline
             * @default []
             */
            timeline: components["schemas"]["EdgeEvent"][];
        };
        /**
         * GraphNode
         * @description 继承 BaseEntity，用于图谱节点
         */
        GraphNode: {
            /**
             * Name
             * @description 实体名称 (如 '孙杰克', '玄天宗')
             */
            name: string;
            /**
             * Type
             * @description 实体类型: Person(人物), Location(地点/自然环境), Organization(组织/社会环境), Item(物品), Concept(概念)
             */
            type: string;
            /**
             * Description
             * @description 相关描述或状态更新
             */
            description: string;
            /**
             * Confidence
             * @description 置信度
             */
            confidence?: number | null;
            /**
             * Count
             * @default 1
             */
            count: number;
            /**
             * Chapter Ids
             * @default []
             */
            chapter_ids: string[];
            /**
             * History
             * @default []
             */
            history: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /** Result */
            result?: unknown | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** NovelInfo */
        NovelInfo: {
            /** Name */
            name: string;
            /** Hashes */
            hashes: string[];
        };
        /**
         * RelationshipInteraction
         * @description 继承 BaseRelationship
         */
        RelationshipInteraction: {
            /**
             * Source
             * @description 主体 (Subject)，如 '孙杰克'
             */
            source: string;
            /**
             * Target
             * @description 客体 (Object)，如 '塔派'
             */
            target: string;
            /**
             * Relation
             * @description 关系类型/谓语，如 '朋友', '敌人', '攻击', '遇见'
             */
            relation: string;
            /**
             * Description
             * @description 关系描述，如 '在垃圾场捡到的机器人'
             */
            description: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Direction
             * @default forward
             */
            direction: string;
        };
        /** RelationshipJobRequest */
        RelationshipJobRequest: {
            /** Novel Name */
            novel_name: string;
            /** File Hash */
            file_hash: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** RelationshipPair */
        RelationshipPair: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** RelationshipTimelineEvent */
        RelationshipTimelineEvent: {
            /** Chapter Id */
            chapter_id: string;
            /** Chapter Index */
            chapter_index: number;
            /** Chapter Title */
            chapter_title: string;
            /**
             * Interactions
             * @default []
             */
            interactions: components["schemas"]["RelationshipInteraction"][];
            /** Narrative State */
            narrative_state?: {
                [key: string]: unknown;
            } | null;
        };
        /** RunInfo */
        RunInfo: {
            /** Timestamp */
            timestamp: string;
            /** File Hash */
            file_hash: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SummarySentence
         * @description 单句总结及其溯源
         */
        SummarySentence: {
            /**
             * Summary Text
             * @description 总结的句子 (LLM 生成)
             */
            summary_text: string;
            /**
             * Source Spans
             * @description 对应的原文片段 (用于点击跳转)
             */
            source_spans?: components["schemas"]["TextSpan"][];
            /**
             * Confidence
             * @description 置信度 (可选)
             */
            confidence?: number | null;
        };
        /**
         * TextSpan
         * @description 表示文本中的一个片段及其位置
         */
        TextSpan: {
            /**
             * Text
             * @description 片段内容
             */
            text: string;
            /**
             * Start Index
             * @description 在原文中的起始字符偏移量
             */
            start_index: number;
            /**
             * End Index
             * @description 在原文中的结束字符偏移量
             */
            end_index: number;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Chapter Id */
            chapter_id: string;
            /** Chapter Index */
            chapter_index: number;
            /** Chapter Title */
            chapter_title: string;
            /** Content */
            content: string[];
            /** Gap Before */
            gap_before: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_novels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovelInfo"][];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
                timestamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterPreview"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
                timestamp: string;
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
                timestamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_data: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
                timestamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
                timestamp: string;
                entity_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relationship_cache: {
        parameters: {
            query: {
                source: string;
                target: string;
            };
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relationship_timeline: {
        parameters: {
            query: {
                source: string;
                target: string;
            };
            header?: never;
            path: {
                novel_name: string;
                file_hash: string;
                timestamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipTimelineEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_batch_relationship_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRelationshipJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_relationship_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
